const CONSTS = {
  UNIT_PIXELS: 100,
  LAND_THICKNESS: 20,
  GRAVITY_DDY: 2000,
  UNIT_MOVE_ROTATION: Math.PI / 12,

  PLAYER_TYPE: 'player',
  PLAYER_WIDTH: 100,
  PLAYER_HEIGHT: 240,
  PLAYER_MOVE_VELOCITY: 300,
  PLAYER_JUMP_VELOCITY: 840,
  PLAYER_HUNTER_MAX_HEALTH: 100,
  PLAYER_DEATH_MAX_HEALTH: 200,

  ATTACK_TYPE: 'attack',

  BULLET_WIDTH: 50,
  BULLET_HEIGHT: 25,
  BULLET_VELOCITY: 1600,
  BULLET_MAX_DISTANCE: 600,
  BULLET_THROTTLE: 600,
  BULLET_DAMAGE: 50,

  SCYTH_ANIMATION_DURATION: 200,
  SCYTH_INTERVAL: 500,
  SCYTH_START_ANGLE: Math.PI / 2,
  SCYTH_END_ANGLE: -Math.PI * 0.3,
  SCYTH_DAMAGE: 100,
  
  ENEMY_TYPE: 'enemy',

  WALKER_WIDTH: 100,
  WALKER_HEIGHT: 200,
  WALKER_MOVE_VELOCITY: 100,
  WALKER_JUMP_VELOCITY: 1200,
  WALKER_MAX_HEALTH: 100,
  WALKER_DAMAGE: 20,
  WALKER_ATTACK_THROTTLE: 1000,

  WALKER_GHOST_WIDTH: 100,
  WALKER_GHOST_HEIGHT: 200,
  WALKER_GHOST_MOVE_VELOCITY: 50,
  WALKER_GHOST_MAX_HEALTH: 100,
  WALKER_GHOST_ATTACK_INTERVAL: 3000,

  GHOST_FIRE_WIDTH: 50,
  GHOST_FIRE_HEIGHT: 50,
  GHOST_FIRE_VELOCITY: 400,
  GHOST_FIRE_MAX_DISTANCE: 1000,
  GHOST_FIRE_DAMAGE: 50,
  GHOST_FIRE_CURVE_VELOCITY: 400,

  VESSEL_RADIUS: 200,
  VESSEL_EYE_RADIUS: 60,
  VESSEL_LEG_WIDTH: 80,
  VESSEL_LEG_HEIGHT: 150,
  VESSEL_MAX_HEALTH: 1000,
}

export default CONSTS
